// <auto-generated />
using Games.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Games.Mvc.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Games.Mvc.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An epic open-world RPG set in a dark fantasy universe.",
                            Name = "The Witcher 3: Wild Hunt",
                            PictureUrl = "https://cdn.cdprojektred.com/thewitcher.com/media/wallpapers/witcher3/full/witcher3_en_3840x2160_blood_and_wine_01_en_3840x2160.jpg",
                            Url = "https://en.cdprojektred.com/games/the-witcher-3-wild-hunt/"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A sprawling Western epic set in a meticulously detailed open world.",
                            Name = "Red Dead Redemption 2",
                            PictureUrl = "https://rockstarintel.com/wp-content/uploads/2018/09/rdr2_main_promo.jpg",
                            Url = "https://www.rockstargames.com/reddeadredemption2/"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A gripping action-adventure game set in a post-apocalyptic world.",
                            Name = "The Last of Us Part II",
                            PictureUrl = "https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/ss_5d720db0b8715f21e73828c80b1b087019d3ef91.jpg",
                            Url = "https://www.playstation.com/en-us/games/the-last-of-us-part-ii/"
                        },
                        new
                        {
                            Id = 4,
                            Description = "An intense action-adventure game based on Norse mythology.",
                            Name = "God of War",
                            PictureUrl = "https://images.g2a.com/newlayout/323x433/1x1x0/821a90e92334/591f16905bafe355be5414aa",
                            Url = "https://www.playstation.com/en-us/games/god-of-war/"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A futuristic open-world RPG set in the sprawling Night City.",
                            Name = "Cyberpunk 2077",
                            PictureUrl = "https://images.ctfassets.net/rporu91m20dc/2y4pAuRvc8gs2I4muVQqG4/6b14f06b8a3ed52f5f3b63ef10e0b1bd/cyberpunk-2077-delays-banner.jpg?w=1920&h=1080&q=90&fm=webp",
                            Url = "https://www.cyberpunk.net/"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Embark on a Viking saga in this open-world action-adventure game.",
                            Name = "Assassin's Creed Valhalla",
                            PictureUrl = "https://cdn1.epicgames.com/ue/product/Screenshot/ac-valhalla-homepage-1920x1080-d0c60a5e5f62a1664814f3bc918c640b.png",
                            Url = "https://www.ubisoft.com/en-us/game/assassins-creed/valhalla"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Journey through feudal Japan in this stunning action-adventure game.",
                            Name = "Ghost of Tsushima",
                            PictureUrl = "https://images.pushsquare.com/screenshots/106108/large.jpg",
                            Url = "https://www.playstation.com/en-us/games/ghost-of-tsushima/"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Swing through the streets of New York as the iconic web-slinger.",
                            Name = "Marvel's Spider-Man",
                            PictureUrl = "https://images-na.ssl-images-amazon.com/images/I/81S5e8Yze8L._SX466_.jpg",
                            Url = "https://www.playstation.com/en-us/games/marvels-spider-man/"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Explore a lush open world inhabited by robotic creatures in this action RPG.",
                            Name = "Horizon Zero Dawn",
                            PictureUrl = "https://static.wikia.nocookie.net/horizonzerodawn/images/1/1c/Horizon_Zero_Dawn_Cover_Art.jpg",
                            Url = "https://www.playstation.com/en-us/games/horizon-zero-dawn/"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Embark on a journey across a post-apocalyptic America in this unique game.",
                            Name = "Death Stranding",
                            PictureUrl = "https://images.pushsquare.com/8968ab3f87fc0/death-stranding-review-lede.original.jpg",
                            Url = "https://www.playstation.com/en-us/games/death-stranding/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
